# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Martin Tierney's Development Blog
email: martin.tierney86@hotmail.co.uk
description: > # this means to ignore newlines until "baseurl:"
  This blog is meant to help me keep track of all the things I learn, if it manages to 
  help someone else at the same time, then that's great!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://martint86.github.io" # the base hostname & protocol for your site
twitter_username: MartinT86
github_username:  MartinT86

# Build settings
markdown: kramdown
